### ISSUE TITLE
UNSETTLED FUNCTION BUG IN HOOK FUNCTION

### ISSUE THREAD

**Issue by lisandi** [ether/ep_subscript_and_superscript#14]
We receive the following RED error messages in Chrome Developer Tools:

VM1001:67 UNSETTLED FUNCTION BUG IN HOOK FUNCTION (plugin: ep_subscript_and_superscript, function name: ep_subscript_and_superscript/static/js/index, hook: aceEditEvent): The hook function neither called the callback nor returned a non-undefined value. This is prohibited because it will result in freezes when a future version of Etherpad updates the hook to support asynchronous behavior.

**Comment by JohnMcLear** [comment]
Just FWIW these errors are benign but do need addressing at some point.

**Comment by JohnMcLear** [comment]
Also AFAIK I don't think aceEditEvent is async which is why this can't be fixed in the plugin.  cc @rhansen for clarity/confirmation :)

**Comment by JohnMcLear** [comment]
Thanks @rhansen
